# Shell variables
# Generated by 'wal'
wallpaper="/home/azryatic/Pictures/Wallpapers/Persona5.jpeg"

# Special
background='#000000'
foreground='#e3e0e0'
cursor='#e3e0e0'

# Colors
color0='#000000'
color1='#ED1E24'
color2='#C53539'
color3='#887F81'
color4='#8C8C8F'
color5='#ABACAD'
color6='#EEA4A6'
color7='#e3e0e0'
color8='#9e9c9c'
color9='#ED1E24'
color10='#C53539'
color11='#887F81'
color12='#8C8C8F'
color13='#ABACAD'
color14='#EEA4A6'
color15='#e3e0e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
