--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/azryatic/Pictures/Wallpapers/Persona5.jpeg"

-- Special
background="#000000"
foreground="#e3e0e0"
cursor="#e3e0e0"

-- Colors
color0="#000000"
color1="#ED1E24"
color2="#C53539"
color3="#887F81"
color4="#8C8C8F"
color5="#ABACAD"
color6="#EEA4A6"
color7="#e3e0e0"
color8="#9e9c9c"
color9="#ED1E24"
color10="#C53539"
color11="#887F81"
color12="#8C8C8F"
color13="#ABACAD"
color14="#EEA4A6"
color15="#e3e0e0"
